const BASE_URL = "../assets/iconos/";

export default {
  sandwich:require(`${BASE_URL}hamburguesa.png`),
  infusiones:require(`${BASE_URL}infusiones.png`),
  cerveza:require(`${BASE_URL}cerveza.png`),
  alcohol:require(`${BASE_URL}alcohol.png`),
  lata:require(`${BASE_URL}lata.png`),
  gaseosa:require(`${BASE_URL}gaseosa.png`),
  vino:require(`${BASE_URL}vino.png`),
  carne:require(`${BASE_URL}carne.png`),
  batido:require(`${BASE_URL}batido.png`),
  botellaAgua:require(`${BASE_URL}botellaAgua.png`),
  cacerola:require(`${BASE_URL}cacerola.png`),
  cafe:require(`${BASE_URL}cafe.png`),
  cerdo:require(`${BASE_URL}cerdo.png`),
  chorizo:require(`${BASE_URL}chorizo.png`),
  coctel:require(`${BASE_URL}coctel.png`),
  combo:require(`${BASE_URL}combo.png`),
  desayuno:require(`${BASE_URL}desayuno.png`),
  empanadas:require(`${BASE_URL}empanadas.png`),
  ensalada:require(`${BASE_URL}ensalada.png`),
  gallina:require(`${BASE_URL}gallina.png`),
  jugos:require(`${BASE_URL}jugos.png`),
  marisco:require(`${BASE_URL}marisco.png`),
  medialuna:require(`${BASE_URL}medialuna.png`),
  muffin:require(`${BASE_URL}muffin.png`),
  pan:require(`${BASE_URL}pan.png`),
  papasfritas:require(`${BASE_URL}papasFritas.png`),
  parrilla:require(`${BASE_URL}parrilla.png`),
  pescado:require(`${BASE_URL}pescado.png`),
  pizza:require(`${BASE_URL}pizza.png`),
  platosCalientes:require(`${BASE_URL}platosCalientes.png`),
  pollo:require(`${BASE_URL}pollo.png`),
  quesos:require(`${BASE_URL}quesos.png`),
  sushi:require(`${BASE_URL}sushi.png`),
  cubiertos:require(`${BASE_URL}cubiertos.png`),
  tragos:require(`${BASE_URL}tragos.png`),
  wisky:require(`${BASE_URL}wisky.png`),
  woks:require(`${BASE_URL}woks.png`),
  vinoBot:require(`${BASE_URL}vinoBot.png`),
  vaca:require(`${BASE_URL}vaca.png`),
  tortas:require(`${BASE_URL}tortas.png`),
  brunch:require(`${BASE_URL}brunch.png`),
  macaron:require(`${BASE_URL}macaron.png`),
  

}
